### ISSUE TITLE
Validate timings in schedule once Day Schedule confirmed

### ISSUE THREAD

**Issue by sedders123** [srobo/sr2022-comp#3]
Once https://github.com/srobo/tasks/issues/743 is merged we should check that the `schedule.yaml` has correct times.

**Comment by WillB97** [comment]
See https://github.com/srobo/tasks/issues/743#issuecomment-1083601659

**Comment by sedders123** [comment]
This was done in https://github.com/srobo/sr2022-comp/pull/7
